export const CATEGORIES = [
  "ENGINE REPAIR",
  "GEAR BOX",
  "ELECTRICAL",
  "BODY WORK",
  "DIFFERENTIAL",
  "TRANSMISSION",
  "AC & COOLING",
  "EATS FLUSHING",
  "GENERAL SERVICE",
  "SCHEDULE SERVICE",
];

export const BRANCHES = [
  "BALLARI",
  "CHITRADURGA",
  "HOSPET",
  "RAICHUR"
];
